Repository umdevclub/umdevclub.github.io, pull requests merged in 2018-03, with the labels that each got.

#37 Creates relevant readme for the project
  README.md
Labels: documentation

#34 Kenny
  index.html
Labels: new content

#38 Moved social media links to footer
  index.html
Labels: enhancement
