Repository umdevclub/umdevclub.github.io, pull requests merged in 2018-02, with the labels that each got.

#19 Enable smooth scrolling when users click on the navigation bar and any other anchor link
  .idea/workspace.xml
  index.html
  js/devclubJS.js
Labels: enhancement

#22 removes idea folder and adds basic gitignore
  .gitignore
  .idea/devClub.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: code cleanup

#25 removes pointer events from span.title elements
  css/style.css
Labels: bug
